spring:
  h2:
    console:
      enabled: true
      path: '/console'

  datasource:
#    url: 'jdbc:h2:file:C:\Users\Administrator\Documents\Work\Projects\spring-library-workshop\library'


  jpa:
    show-sql: true
    hibernate:

      ddl-auto: validate

  webflux:
          static-path-pattern=/resources/static/
